<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FacilitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('facilities')->insert([
            [
                'facility_name' => 'Mary Thomas Building (MT)',
                'description' => 'Insert a descriptive facility description here.',
                'maximum_rental_hour' => 5,
                'category_id' => 1,
                'subcategory_id' => 2,
                'location_note' => 'Near gate 3',
                'capacity' => 500,
                'department_id' => 4,
                'location_type' => 'Indoors',
                'internal_fee' => 500.00,
                'external_fee' => 650.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => 'Mary Thomas Computer Lab (MTCL)',
                'description' => '',
                'maximum_rental_hour' => 12,
                'category_id' => 1,
                'subcategory_id' => 1,
                'location_note' => '',
                'capacity' => null,
                'department_id' => null,
                'location_type' => null,
                'internal_fee' => null,
                'external_fee' => null,
                'rate_type' => null,
                'status_id' => null,
                'last_booked_at' => null,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => '',
                'description' => '',
                'maximum_rental_hour' => null,
                'category_id' => null,
                'subcategory_id' => null,
                'location_note' => '',
                'capacity' => null,
                'department_id' => null,
                'location_type' => null,
                'internal_fee' => null,
                'external_fee' => null,
                'rate_type' => null,
                'status_id' => null,
                'last_booked_at' => null,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => '',
                'description' => '',
                'maximum_rental_hour' => null,
                'category_id' => null,
                'subcategory_id' => null,
                'location_note' => '',
                'capacity' => null,
                'department_id' => null,
                'location_type' => null,
                'internal_fee' => null,
                'external_fee' => null,
                'rate_type' => null,
                'status_id' => null,
                'last_booked_at' => null,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => '',
                'description' => '',
                'maximum_rental_hour' => null,
                'category_id' => null,
                'subcategory_id' => null,
                'location_note' => '',
                'capacity' => null,
                'department_id' => null,
                'location_type' => null,
                'internal_fee' => null,
                'external_fee' => null,
                'rate_type' => null,
                'status_id' => null,
                'last_booked_at' => null,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => '',
                'description' => '',
                'maximum_rental_hour' => null,
                'category_id' => null,
                'subcategory_id' => null,
                'location_note' => '',
                'capacity' => null,
                'department_id' => null,
                'location_type' => null,
                'internal_fee' => null,
                'external_fee' => null,
                'rate_type' => null,
                'status_id' => null,
                'last_booked_at' => null,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => '',
                'description' => '',
                'maximum_rental_hour' => null,
                'category_id' => null,
                'subcategory_id' => null,
                'location_note' => '',
                'capacity' => null,
                'department_id' => null,
                'location_type' => null,
                'internal_fee' => null,
                'external_fee' => null,
                'rate_type' => null,
                'status_id' => null,
                'last_booked_at' => null,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => '',
                'description' => '',
                'maximum_rental_hour' => null,
                'category_id' => null,
                'subcategory_id' => null,
                'location_note' => '',
                'capacity' => null,
                'department_id' => null,
                'location_type' => null,
                'internal_fee' => null,
                'external_fee' => null,
                'rate_type' => null,
                'status_id' => null,
                'last_booked_at' => null,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
