<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FacilitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('facilities')->insert([
            [
                'facility_name' => 'Rose Memorial Auditorium',
                'description' => 'A venue typically used for large-scale events, performances, and ceremonies.',
                'maximum_rental_hour' => null,
                'category_id' => 1,
                'subcategory_id' => 4,
                'capacity' => 2300,
                'department_id' => 4,
                'location_type' => 'Indoors',
                'internal_fee' => 3500.00,
                'external_fee' => 3500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'room_code' => null,
                'floor_level' => null,
                'building_code' => 'RMA',
                'total_levels' => 2,
                'total_rooms' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => 'Mary Thomas Computer Lab (MTCL)',
                'description' => '',
                'maximum_rental_hour' => 12,
                'category_id' => 1,
                'subcategory_id' => 2,
                'capacity' => 100,
                'department_id' => 4,
                'location_type' => 'Indoors',
                'internal_fee' => 3500.00,
                'external_fee' => 3500.00,
                'rate_type' => 'Per Event',
                'status_id' => 2,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'room_code' => null,
                'floor_level' => null,
                'building_code' => 'RMA',
                'total_levels' => 2,
                'total_rooms' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => 'Old Valentine Building (OV)',
                'description' => '',
                'maximum_rental_hour' => 10,
                'category_id' => 1,
                'subcategory_id' => 2,
                'capacity' => 200,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'internal_fee' => 200.00,
                'external_fee' => 300.00,
                'rate_type' => 'Per Hour',
                'status_id' => 3,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'room_code' => null,
                'floor_level' => null,
                'building_code' => 'OV',
                'total_levels' => 2,
                'total_rooms' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => 'Rose Memorial Auditorium (RMA)',
                'description' => '',
                'maximum_rental_hour' => 12,
                'category_id' => 1,
                'subcategory_id' => 4,
                'capacity' => 1,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'internal_fee' => 250.00,
                'external_fee' => 350.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'room_code' => null,
                'floor_level' => null,
                'building_code' => 'RMA',
                'total_levels' => 1,
                'total_rooms' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => 'Unniversity Church',
                'description' => '',
                'maximum_rental_hour' => 12,
                'category_id' => 1,
                'subcategory_id' => 3,
                'capacity' => 50,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'internal_fee' => 300.00,
                'external_fee' => 400.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'room_code' => null,
                'floor_level' => 1,
                'building_code' => 'UC',
                'total_levels' => 1,
                'total_rooms' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => 'University Swimming Pool',
                'description' => '',
                'maximum_rental_hour' => 4,
                'category_id' => 5,
                'subcategory_id' => 4,
                'capacity' => 50,
                'department_id' => 1,
                'location_type' => 'Outdoors',
                'internal_fee' => 200.00,
                'external_fee' => 300.00,
                'rate_type' => 'Per Hour',
                'status_id' => 2,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'room_code' => null,
                'floor_level' => null,
                'building_code' => null,
                'total_levels' => null,
                'total_rooms' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => 'University Gymnasium (UG)',
                'description' => 'A multi-purpose sports facility for various athletic activities and events.',
                'maximum_rental_hour' => null,
                'category_id' => 5,
                'subcategory_id' => 19,
                'capacity' => 6200,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'internal_fee' => 10000.00,
                'external_fee' => 10000.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'room_code' => null,
                'floor_level' => 1,
                'building_code' => 'UG',
                'total_levels' => 1,
                'total_rooms' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => 'Promenade Park',
                'description' => '',
                'maximum_rental_hour' => 12,
                'category_id' => 4,
                'subcategory_id' => 3,
                'capacity' => 100,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'internal_fee' => 400.00,
                'external_fee' => 500.00,
                'rate_type' => 'Per Event',
                'status_id' => 2,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'room_code' => null,
                'floor_level' => 1,
                'building_code' => null,
                'total_levels' => 1,
                'total_rooms' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => 'Halfmoon Drive',
                'description' => '',
                'maximum_rental_hour' => 12,
                'category_id' => 4,
                'subcategory_id' => 2,
                'capacity' => 100,
                'department_id' => 1,
                'location_type' => 'Outdoors',
                'internal_fee' => 200.00,
                'external_fee' => 350.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'room_code' => null,
                'floor_level' => null,
                'building_code' => null,
                'total_levels' => null,
                'total_rooms' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_name' => 'Mary Thomas Computer Lab #1',
                'description' => '',
                'maximum_rental_hour' => 12,
                'category_id' => 2,
                'subcategory_id' => 3,
                'capacity' => 20,
                'department_id' => 4,
                'location_type' => 'Indoors',
                'internal_fee' => 100.00,
                'external_fee' => 250.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => 1,
                'room_code' => 'MTCL1',
                'floor_level' => 2,
                'building_code' => null,
                'total_levels' => null,
                'total_rooms' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
