<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FacilityImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('facility_images')->insert([
            [
                'facility_id' => 1,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Primary image for Mary Thomas Building',
                'sort_order' => 1,
                'image_type' => 'Primary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 1,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Secondary image for Mary Thomas Building',
                'sort_order' => 2,
                'image_type' => 'Secondary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 2,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Primary image for Mary Thomas Computer Lab',
                'sort_order' => 1,
                'image_type' => 'Primary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 2,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Secondary image for Mary Thomas Computer Lab',
                'sort_order' => 2,
                'image_type' => 'Secondary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 3,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Primary image for Old Valentine Building',
                'sort_order' => 1,
                'image_type' => 'Primary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 3,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Secondary image for Old Valentine Building',
                'sort_order' => 2,
                'image_type' => 'Secondary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 4,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Primary image for Rose Memorial Auditorium',
                'sort_order' => 1,
                'image_type' => 'Primary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 4,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Secondary image for Rose Memorial Auditorium',
                'sort_order' => 2,
                'image_type' => 'Secondary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 5,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Primary image for University Church',
                'sort_order' => 1,
                'image_type' => 'Primary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 5,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Secondary image for University Church',
                'sort_order' => 2,
                'image_type' => 'Secondary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 6,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Primary image for University Swimming Pool',
                'sort_order' => 1,
                'image_type' => 'Primary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 6,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Secondary image for University Swimming Pool',
                'sort_order' => 2,
                'image_type' => 'Secondary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 7,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Primary image for University Gym',
                'sort_order' => 1,
                'image_type' => 'Primary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 7,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Secondary image for University Gym',
                'sort_order' => 2,
                'image_type' => 'Secondary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 8,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Primary image for Promenade Park',
                'sort_order' => 1,
                'image_type' => 'Primary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 8,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Secondary image for Promenade Park',
                'sort_order' => 2,
                'image_type' => 'Secondary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 9,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Primary image for Halfmoon Drive',
                'sort_order' => 1,
                'image_type' => 'Primary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 9,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Secondary image for Halfmoon Drive',
                'sort_order' => 2,
                'image_type' => 'Secondary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 10,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Primary image for Mary Thomas Computer Lab #1',
                'sort_order' => 1,
                'image_type' => 'Primary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_id' => 10,
                'image_url' => 'https://res.cloudinary.com/dn98ntlkd/image/upload/v1750895337/oxvsxogzu9koqhctnf7s.webp',
                'cloudinary_public_id' => 'oxvsxogzu9koqhctnf7s',
                'description' => 'Secondary image for Mary Thomas Computer Lab #1',
                'sort_order' => 2,
                'image_type' => 'Secondary',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
